"""inital tables

Revision ID: e412fae9638a
Revises:
Create Date: 2026-03-14 21:10:58.644015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e412fae9638a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("access_level", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "credential",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", name="credential_account_id_ukey"),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=15), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", name="user_profile_account_id_ukey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
        schema="development",
    )
    op.create_table(
        "location",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("street_address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column(
            "tier_level", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column("manager_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(),
            server_default=sa.text("'inactive'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["development.company.id"],
            name=op.f("location_company_id_fk"),
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["development.credential.id"],
            name=op.f("location_manager_fk"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("location_pk")),
        schema="development",
    )
    op.create_table(
        "credential",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["role"],
            ["development.access_levels.role_name"],
            name=op.f("credential_access_levels_role_name_fk"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("credential_pkey")),
        schema="development",
    )
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
    )
    op.create_table(
        "access_levels",
        sa.Column(
            "role_name", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column("access_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("role_name", name=op.f("access_levels_pk")),
        schema="development",
    )
    op.create_table(
        "account",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("location", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("account_pkey")),
        schema="development",
    )
    op.create_table(
        "forms",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "layout",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("access_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("table", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="development",
    )
    op.create_table(
        "anilox",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("anilox_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("lpi", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("bcm", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column(
            "milage",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("manufacturer", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("location_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cell_angle", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "inventory_location", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("material", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("length", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("diameter", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("cell_shape", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("purchase_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["development.location.id"],
            name=op.f("anilox_location_id_fk"),
        ),
        schema="development",
    )
    op.create_table(
        "company",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "invite_token", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
        sa.Column(
            "status",
            sa.VARCHAR(),
            server_default=sa.text("'Active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("company_pk")),
        schema="development",
    )
    # ### end Alembic commands ###
